services:
  web:
    build: .
    container_name: rails_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./secrets.env:/run/secrets/my_app.env:ro
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_pass

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    secrets:
      - postgres_pass
    entrypoint: >
      sh -c '
        export DATA_SOURCE_NAME="postgresql://postgres:$(cat /run/secrets/postgres_pass)@db:5432/postgres?sslmode=disable";
        /bin/postgres_exporter
      '
    depends_on:
      - db

  redis_exporter:
    image: oliver006/redis_exporter
    command: --redis.addr=redis://redis:6379
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerting_rules.yml:/etc/prometheus/alerting_rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager

secrets:
  postgres_pass:
    file: postgres_pass.txt

volumes:
  pgdata:
  grafana-storage:
