groups:
  - name: rails_alerts
    rules:
      - alert: RailsAppDown
        expr: up{job="rails_app"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Rails app down"
          description: "Cannot get rails_app metrics for 30 seconds"

      - alert: HighRailsMemoryUsage
        expr: process_resident_memory_bytes{job="rails_app"} > 500000000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Rails high memmory usage"
          description: "Rails process memory usage exceeds 500MB"

      - alert: RailsAppHighCPU
        expr: rate(process_cpu_seconds_total{job="rails_app"}[1m]) > 0.8
        for: 2m
        labels:
          severity: warning
          service: rails_app
        annotations:
          summary: "High CPU usage"
          description: "The Rails process is using more than 80% of the CPU in the last 2 minutes"

  - name: redis_alerts
    rules:
      - alert: RedisUnavailable
        expr: up{job="redis_exporter"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Redis service down"
          description: "No Redis metrics available for 30 seconds"
      
      - alert: RedisTooManyConnections
        expr: redis_connected_clients{job="redis_exporter"} > 100
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Too many active connections"
          description: "There are more than 100 clients connected to Redis. Possible connection leak or overload"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes{job="redis_exporter"} > 500000000
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "High memmory usage"
          description: "Redis is using more than 500MB of memory. Review your configuration or usage patterns"

      - alert: RedisCacheHit
        expr: redis_keyspace_hits_total / (redis_keyspace_hits_total + redis_keyspace_misses_total) < 0.8
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Low cache hit ratio"
          description: "Low Redis cache hit ratio in the last 2 minutes"

  - name: postgres_alerts
    rules:
      - alert: PostgresDown
        expr: pg_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL down"
          description: "PostgreSQL exporter do not respond"

      - alert: PostgresSlowQueries
        expr: rate(pg_stat_activity_count{state="active"}[1m]) > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL: Too many active requests"
          description: "More than 50 active requests in the last minutes"

      - alert: PostgresDBSize
        expr: pg_database_size_bytes{job="postgres_exporter"} > 10000000000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL DB almost full"
          description: "PostgreSQL database has almost reached its full capacity"

      - alert: PostgresCacheHit
        expr: pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read) < 0.7
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL low cache hit ratio"
          description: "Low PostgreSQL cache hit ratio in the last 2 minutes"
